#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manhua
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertslideshow(slideshow instance);
    partial void Updateslideshow(slideshow instance);
    partial void Deleteslideshow(slideshow instance);
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertComicCreator(ComicCreator instance);
    partial void UpdateComicCreator(ComicCreator instance);
    partial void DeleteComicCreator(ComicCreator instance);
    partial void InsertFavourite(Favourite instance);
    partial void UpdateFavourite(Favourite instance);
    partial void DeleteFavourite(Favourite instance);
    partial void Insertreaders(readers instance);
    partial void Updatereaders(readers instance);
    partial void Deletereaders(readers instance);
    partial void InsertEpisode(Episode instance);
    partial void UpdateEpisode(Episode instance);
    partial void DeleteEpisode(Episode instance);
    partial void InsertComic(Comic instance);
    partial void UpdateComic(Comic instance);
    partial void DeleteComic(Comic instance);
    partial void Insertpayment(payment instance);
    partial void Updatepayment(payment instance);
    partial void Deletepayment(payment instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<slideshow> slideshows
		{
			get
			{
				return this.GetTable<slideshow>();
			}
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<ComicCreator> ComicCreators
		{
			get
			{
				return this.GetTable<ComicCreator>();
			}
		}
		
		public System.Data.Linq.Table<Favourite> Favourites
		{
			get
			{
				return this.GetTable<Favourite>();
			}
		}
		
		public System.Data.Linq.Table<readers> readers
		{
			get
			{
				return this.GetTable<readers>();
			}
		}
		
		public System.Data.Linq.Table<Episode> Episodes
		{
			get
			{
				return this.GetTable<Episode>();
			}
		}
		
		public System.Data.Linq.Table<Comic> Comics
		{
			get
			{
				return this.GetTable<Comic>();
			}
		}
		
		public System.Data.Linq.Table<payment> payments
		{
			get
			{
				return this.GetTable<payment>();
			}
		}
		
		public System.Data.Linq.Table<ComicPurchased> ComicPurchaseds
		{
			get
			{
				return this.GetTable<ComicPurchased>();
			}
		}
		
		public System.Data.Linq.Table<Member> Members
		{
			get
			{
				return this.GetTable<Member>();
			}
		}
		
		public System.Data.Linq.Table<Purchased> Purchaseds
		{
			get
			{
				return this.GetTable<Purchased>();
			}
		}
		
		public System.Data.Linq.Table<TempCategory> TempCategories
		{
			get
			{
				return this.GetTable<TempCategory>();
			}
		}
		
		public System.Data.Linq.Table<TopCategory> TopCategories
		{
			get
			{
				return this.GetTable<TopCategory>();
			}
		}
		
		public System.Data.Linq.Table<ComicInfo> ComicInfos
		{
			get
			{
				return this.GetTable<ComicInfo>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<Profit> Profits
		{
			get
			{
				return this.GetTable<Profit>();
			}
		}
		
		public System.Data.Linq.Table<TopComic> TopComics
		{
			get
			{
				return this.GetTable<TopComic>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _A_Id;
		
		private string _A_Nickname;
		
		private string _A_hash;
		
		private string _A_email;
		
		private System.Nullable<char> _A_gender;
		
		private bool _A_status;
		
		private System.DateTime _A_register_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnA_IdChanging(int value);
    partial void OnA_IdChanged();
    partial void OnA_NicknameChanging(string value);
    partial void OnA_NicknameChanged();
    partial void OnA_hashChanging(string value);
    partial void OnA_hashChanged();
    partial void OnA_emailChanging(string value);
    partial void OnA_emailChanged();
    partial void OnA_genderChanging(System.Nullable<char> value);
    partial void OnA_genderChanged();
    partial void OnA_statusChanging(bool value);
    partial void OnA_statusChanged();
    partial void OnA_register_dateChanging(System.DateTime value);
    partial void OnA_register_dateChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int A_Id
		{
			get
			{
				return this._A_Id;
			}
			set
			{
				if ((this._A_Id != value))
				{
					this.OnA_IdChanging(value);
					this.SendPropertyChanging();
					this._A_Id = value;
					this.SendPropertyChanged("A_Id");
					this.OnA_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Nickname", DbType="VarChar(50)")]
		public string A_Nickname
		{
			get
			{
				return this._A_Nickname;
			}
			set
			{
				if ((this._A_Nickname != value))
				{
					this.OnA_NicknameChanging(value);
					this.SendPropertyChanging();
					this._A_Nickname = value;
					this.SendPropertyChanged("A_Nickname");
					this.OnA_NicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_hash", DbType="VarChar(50)")]
		public string A_hash
		{
			get
			{
				return this._A_hash;
			}
			set
			{
				if ((this._A_hash != value))
				{
					this.OnA_hashChanging(value);
					this.SendPropertyChanging();
					this._A_hash = value;
					this.SendPropertyChanged("A_hash");
					this.OnA_hashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string A_email
		{
			get
			{
				return this._A_email;
			}
			set
			{
				if ((this._A_email != value))
				{
					this.OnA_emailChanging(value);
					this.SendPropertyChanging();
					this._A_email = value;
					this.SendPropertyChanged("A_email");
					this.OnA_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_gender", DbType="Char(1)")]
		public System.Nullable<char> A_gender
		{
			get
			{
				return this._A_gender;
			}
			set
			{
				if ((this._A_gender != value))
				{
					this.OnA_genderChanging(value);
					this.SendPropertyChanging();
					this._A_gender = value;
					this.SendPropertyChanged("A_gender");
					this.OnA_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_status", DbType="Bit NOT NULL")]
		public bool A_status
		{
			get
			{
				return this._A_status;
			}
			set
			{
				if ((this._A_status != value))
				{
					this.OnA_statusChanging(value);
					this.SendPropertyChanging();
					this._A_status = value;
					this.SendPropertyChanged("A_status");
					this.OnA_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_register_date", DbType="DateTime NOT NULL")]
		public System.DateTime A_register_date
		{
			get
			{
				return this._A_register_date;
			}
			set
			{
				if ((this._A_register_date != value))
				{
					this.OnA_register_dateChanging(value);
					this.SendPropertyChanging();
					this._A_register_date = value;
					this.SendPropertyChanged("A_register_date");
					this.OnA_register_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.slideshow")]
	public partial class slideshow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _S_Id;
		
		private string _S_Title;
		
		private string _S_link;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_IdChanging(int value);
    partial void OnS_IdChanged();
    partial void OnS_TitleChanging(string value);
    partial void OnS_TitleChanged();
    partial void OnS_linkChanging(string value);
    partial void OnS_linkChanged();
    #endregion
		
		public slideshow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int S_Id
		{
			get
			{
				return this._S_Id;
			}
			set
			{
				if ((this._S_Id != value))
				{
					this.OnS_IdChanging(value);
					this.SendPropertyChanging();
					this._S_Id = value;
					this.SendPropertyChanged("S_Id");
					this.OnS_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string S_Title
		{
			get
			{
				return this._S_Title;
			}
			set
			{
				if ((this._S_Title != value))
				{
					this.OnS_TitleChanging(value);
					this.SendPropertyChanging();
					this._S_Title = value;
					this.SendPropertyChanged("S_Title");
					this.OnS_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_link", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string S_link
		{
			get
			{
				return this._S_link;
			}
			set
			{
				if ((this._S_link != value))
				{
					this.OnS_linkChanging(value);
					this.SendPropertyChanging();
					this._S_link = value;
					this.SendPropertyChanged("S_link");
					this.OnS_linkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ca_Id;
		
		private string _Ca_Name;
		
		private EntitySet<Comic> _Comics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCa_IdChanging(string value);
    partial void OnCa_IdChanged();
    partial void OnCa_NameChanging(string value);
    partial void OnCa_NameChanged();
    #endregion
		
		public Category()
		{
			this._Comics = new EntitySet<Comic>(new Action<Comic>(this.attach_Comics), new Action<Comic>(this.detach_Comics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ca.Id]", Storage="_Ca_Id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ca_Id
		{
			get
			{
				return this._Ca_Id;
			}
			set
			{
				if ((this._Ca_Id != value))
				{
					this.OnCa_IdChanging(value);
					this.SendPropertyChanging();
					this._Ca_Id = value;
					this.SendPropertyChanged("Ca_Id");
					this.OnCa_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ca.Name]", Storage="_Ca_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ca_Name
		{
			get
			{
				return this._Ca_Name;
			}
			set
			{
				if ((this._Ca_Name != value))
				{
					this.OnCa_NameChanging(value);
					this.SendPropertyChanging();
					this._Ca_Name = value;
					this.SendPropertyChanged("Ca_Name");
					this.OnCa_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Comic", Storage="_Comics", ThisKey="Ca_Id", OtherKey="C_category")]
		public EntitySet<Comic> Comics
		{
			get
			{
				return this._Comics;
			}
			set
			{
				this._Comics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comics(Comic entity)
		{
			this.SendPropertyChanging();
			entity.Category = this;
		}
		
		private void detach_Comics(Comic entity)
		{
			this.SendPropertyChanging();
			entity.Category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ComicCreator")]
	public partial class ComicCreator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CC_Id;
		
		private string _CC_NickName;
		
		private string _CC_hash;
		
		private string _CC_email;
		
		private System.Nullable<System.DateTime> _CC_birth_date;
		
		private string _CC_phone;
		
		private System.Nullable<char> _CC_gender;
		
		private bool _CC_isvip;
		
		private bool _CC_BanStatus;
		
		private System.DateTime _CC_register_date;
		
		private bool _CC_EmailVerify;
		
		private EntitySet<Comic> _Comics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCC_IdChanging(int value);
    partial void OnCC_IdChanged();
    partial void OnCC_NickNameChanging(string value);
    partial void OnCC_NickNameChanged();
    partial void OnCC_hashChanging(string value);
    partial void OnCC_hashChanged();
    partial void OnCC_emailChanging(string value);
    partial void OnCC_emailChanged();
    partial void OnCC_birth_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnCC_birth_dateChanged();
    partial void OnCC_phoneChanging(string value);
    partial void OnCC_phoneChanged();
    partial void OnCC_genderChanging(System.Nullable<char> value);
    partial void OnCC_genderChanged();
    partial void OnCC_isvipChanging(bool value);
    partial void OnCC_isvipChanged();
    partial void OnCC_BanStatusChanging(bool value);
    partial void OnCC_BanStatusChanged();
    partial void OnCC_register_dateChanging(System.DateTime value);
    partial void OnCC_register_dateChanged();
    partial void OnCC_EmailVerifyChanging(bool value);
    partial void OnCC_EmailVerifyChanged();
    #endregion
		
		public ComicCreator()
		{
			this._Comics = new EntitySet<Comic>(new Action<Comic>(this.attach_Comics), new Action<Comic>(this.detach_Comics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CC_Id
		{
			get
			{
				return this._CC_Id;
			}
			set
			{
				if ((this._CC_Id != value))
				{
					this.OnCC_IdChanging(value);
					this.SendPropertyChanging();
					this._CC_Id = value;
					this.SendPropertyChanged("CC_Id");
					this.OnCC_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_NickName", DbType="VarChar(50)")]
		public string CC_NickName
		{
			get
			{
				return this._CC_NickName;
			}
			set
			{
				if ((this._CC_NickName != value))
				{
					this.OnCC_NickNameChanging(value);
					this.SendPropertyChanging();
					this._CC_NickName = value;
					this.SendPropertyChanged("CC_NickName");
					this.OnCC_NickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_hash", DbType="VarChar(50)")]
		public string CC_hash
		{
			get
			{
				return this._CC_hash;
			}
			set
			{
				if ((this._CC_hash != value))
				{
					this.OnCC_hashChanging(value);
					this.SendPropertyChanging();
					this._CC_hash = value;
					this.SendPropertyChanged("CC_hash");
					this.OnCC_hashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CC_email
		{
			get
			{
				return this._CC_email;
			}
			set
			{
				if ((this._CC_email != value))
				{
					this.OnCC_emailChanging(value);
					this.SendPropertyChanging();
					this._CC_email = value;
					this.SendPropertyChanged("CC_email");
					this.OnCC_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_birth_date", DbType="Date")]
		public System.Nullable<System.DateTime> CC_birth_date
		{
			get
			{
				return this._CC_birth_date;
			}
			set
			{
				if ((this._CC_birth_date != value))
				{
					this.OnCC_birth_dateChanging(value);
					this.SendPropertyChanging();
					this._CC_birth_date = value;
					this.SendPropertyChanged("CC_birth_date");
					this.OnCC_birth_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_phone", DbType="VarChar(11)")]
		public string CC_phone
		{
			get
			{
				return this._CC_phone;
			}
			set
			{
				if ((this._CC_phone != value))
				{
					this.OnCC_phoneChanging(value);
					this.SendPropertyChanging();
					this._CC_phone = value;
					this.SendPropertyChanged("CC_phone");
					this.OnCC_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_gender", DbType="Char(1)")]
		public System.Nullable<char> CC_gender
		{
			get
			{
				return this._CC_gender;
			}
			set
			{
				if ((this._CC_gender != value))
				{
					this.OnCC_genderChanging(value);
					this.SendPropertyChanging();
					this._CC_gender = value;
					this.SendPropertyChanged("CC_gender");
					this.OnCC_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_isvip", DbType="Bit NOT NULL")]
		public bool CC_isvip
		{
			get
			{
				return this._CC_isvip;
			}
			set
			{
				if ((this._CC_isvip != value))
				{
					this.OnCC_isvipChanging(value);
					this.SendPropertyChanging();
					this._CC_isvip = value;
					this.SendPropertyChanged("CC_isvip");
					this.OnCC_isvipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_BanStatus", DbType="Bit NOT NULL")]
		public bool CC_BanStatus
		{
			get
			{
				return this._CC_BanStatus;
			}
			set
			{
				if ((this._CC_BanStatus != value))
				{
					this.OnCC_BanStatusChanging(value);
					this.SendPropertyChanging();
					this._CC_BanStatus = value;
					this.SendPropertyChanged("CC_BanStatus");
					this.OnCC_BanStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_register_date", DbType="DateTime NOT NULL")]
		public System.DateTime CC_register_date
		{
			get
			{
				return this._CC_register_date;
			}
			set
			{
				if ((this._CC_register_date != value))
				{
					this.OnCC_register_dateChanging(value);
					this.SendPropertyChanging();
					this._CC_register_date = value;
					this.SendPropertyChanged("CC_register_date");
					this.OnCC_register_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_EmailVerify", DbType="Bit NOT NULL")]
		public bool CC_EmailVerify
		{
			get
			{
				return this._CC_EmailVerify;
			}
			set
			{
				if ((this._CC_EmailVerify != value))
				{
					this.OnCC_EmailVerifyChanging(value);
					this.SendPropertyChanging();
					this._CC_EmailVerify = value;
					this.SendPropertyChanged("CC_EmailVerify");
					this.OnCC_EmailVerifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ComicCreator_Comic", Storage="_Comics", ThisKey="CC_Id", OtherKey="CC_Id")]
		public EntitySet<Comic> Comics
		{
			get
			{
				return this._Comics;
			}
			set
			{
				this._Comics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comics(Comic entity)
		{
			this.SendPropertyChanging();
			entity.ComicCreator = this;
		}
		
		private void detach_Comics(Comic entity)
		{
			this.SendPropertyChanging();
			entity.ComicCreator = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Favourite")]
	public partial class Favourite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_Id;
		
		private int _C_Id;
		
		private EntityRef<readers> _readers;
		
		private EntityRef<Comic> _Comic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_IdChanging(int value);
    partial void OnR_IdChanged();
    partial void OnC_IdChanging(int value);
    partial void OnC_IdChanged();
    #endregion
		
		public Favourite()
		{
			this._readers = default(EntityRef<readers>);
			this._Comic = default(EntityRef<Comic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int R_Id
		{
			get
			{
				return this._R_Id;
			}
			set
			{
				if ((this._R_Id != value))
				{
					if (this._readers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnR_IdChanging(value);
					this.SendPropertyChanging();
					this._R_Id = value;
					this.SendPropertyChanged("R_Id");
					this.OnR_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int C_Id
		{
			get
			{
				return this._C_Id;
			}
			set
			{
				if ((this._C_Id != value))
				{
					if (this._Comic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnC_IdChanging(value);
					this.SendPropertyChanging();
					this._C_Id = value;
					this.SendPropertyChanged("C_Id");
					this.OnC_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="readers_Favourite", Storage="_readers", ThisKey="R_Id", OtherKey="R_Id", IsForeignKey=true)]
		public readers readers
		{
			get
			{
				return this._readers.Entity;
			}
			set
			{
				readers previousValue = this._readers.Entity;
				if (((previousValue != value) 
							|| (this._readers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._readers.Entity = null;
						previousValue.Favourites.Remove(this);
					}
					this._readers.Entity = value;
					if ((value != null))
					{
						value.Favourites.Add(this);
						this._R_Id = value.R_Id;
					}
					else
					{
						this._R_Id = default(int);
					}
					this.SendPropertyChanged("readers");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comic_Favourite", Storage="_Comic", ThisKey="C_Id", OtherKey="C_Id", IsForeignKey=true)]
		public Comic Comic
		{
			get
			{
				return this._Comic.Entity;
			}
			set
			{
				Comic previousValue = this._Comic.Entity;
				if (((previousValue != value) 
							|| (this._Comic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Comic.Entity = null;
						previousValue.Favourites.Remove(this);
					}
					this._Comic.Entity = value;
					if ((value != null))
					{
						value.Favourites.Add(this);
						this._C_Id = value.C_Id;
					}
					else
					{
						this._C_Id = default(int);
					}
					this.SendPropertyChanged("Comic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reader")]
	public partial class readers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_Id;
		
		private string _R_NickName;
		
		private string _R_hash;
		
		private string _R_email;
		
		private System.Nullable<System.DateTime> _R_birth_date;
		
		private string _R_phone;
		
		private System.Nullable<char> _R_gender;
		
		private bool _R_isvip;
		
		private bool _R_BanStatus;
		
		private System.DateTime _R_register_date;
		
		private bool _R_EmailVerify;
		
		private EntitySet<Favourite> _Favourites;
		
		private EntitySet<payment> _payments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_IdChanging(int value);
    partial void OnR_IdChanged();
    partial void OnR_NickNameChanging(string value);
    partial void OnR_NickNameChanged();
    partial void OnR_hashChanging(string value);
    partial void OnR_hashChanged();
    partial void OnR_emailChanging(string value);
    partial void OnR_emailChanged();
    partial void OnR_birth_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnR_birth_dateChanged();
    partial void OnR_phoneChanging(string value);
    partial void OnR_phoneChanged();
    partial void OnR_genderChanging(System.Nullable<char> value);
    partial void OnR_genderChanged();
    partial void OnR_isvipChanging(bool value);
    partial void OnR_isvipChanged();
    partial void OnR_BanStatusChanging(bool value);
    partial void OnR_BanStatusChanged();
    partial void OnR_register_dateChanging(System.DateTime value);
    partial void OnR_register_dateChanged();
    partial void OnR_EmailVerifyChanging(bool value);
    partial void OnR_EmailVerifyChanged();
    #endregion
		
		public readers()
		{
			this._Favourites = new EntitySet<Favourite>(new Action<Favourite>(this.attach_Favourites), new Action<Favourite>(this.detach_Favourites));
			this._payments = new EntitySet<payment>(new Action<payment>(this.attach_payments), new Action<payment>(this.detach_payments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int R_Id
		{
			get
			{
				return this._R_Id;
			}
			set
			{
				if ((this._R_Id != value))
				{
					this.OnR_IdChanging(value);
					this.SendPropertyChanging();
					this._R_Id = value;
					this.SendPropertyChanged("R_Id");
					this.OnR_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_NickName", DbType="VarChar(50)")]
		public string R_NickName
		{
			get
			{
				return this._R_NickName;
			}
			set
			{
				if ((this._R_NickName != value))
				{
					this.OnR_NickNameChanging(value);
					this.SendPropertyChanging();
					this._R_NickName = value;
					this.SendPropertyChanged("R_NickName");
					this.OnR_NickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_hash", DbType="VarChar(50)")]
		public string R_hash
		{
			get
			{
				return this._R_hash;
			}
			set
			{
				if ((this._R_hash != value))
				{
					this.OnR_hashChanging(value);
					this.SendPropertyChanging();
					this._R_hash = value;
					this.SendPropertyChanged("R_hash");
					this.OnR_hashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string R_email
		{
			get
			{
				return this._R_email;
			}
			set
			{
				if ((this._R_email != value))
				{
					this.OnR_emailChanging(value);
					this.SendPropertyChanging();
					this._R_email = value;
					this.SendPropertyChanged("R_email");
					this.OnR_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_birth_date", DbType="Date")]
		public System.Nullable<System.DateTime> R_birth_date
		{
			get
			{
				return this._R_birth_date;
			}
			set
			{
				if ((this._R_birth_date != value))
				{
					this.OnR_birth_dateChanging(value);
					this.SendPropertyChanging();
					this._R_birth_date = value;
					this.SendPropertyChanged("R_birth_date");
					this.OnR_birth_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_phone", DbType="VarChar(11)")]
		public string R_phone
		{
			get
			{
				return this._R_phone;
			}
			set
			{
				if ((this._R_phone != value))
				{
					this.OnR_phoneChanging(value);
					this.SendPropertyChanging();
					this._R_phone = value;
					this.SendPropertyChanged("R_phone");
					this.OnR_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_gender", DbType="Char(1)")]
		public System.Nullable<char> R_gender
		{
			get
			{
				return this._R_gender;
			}
			set
			{
				if ((this._R_gender != value))
				{
					this.OnR_genderChanging(value);
					this.SendPropertyChanging();
					this._R_gender = value;
					this.SendPropertyChanged("R_gender");
					this.OnR_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_isvip", DbType="Bit NOT NULL")]
		public bool R_isvip
		{
			get
			{
				return this._R_isvip;
			}
			set
			{
				if ((this._R_isvip != value))
				{
					this.OnR_isvipChanging(value);
					this.SendPropertyChanging();
					this._R_isvip = value;
					this.SendPropertyChanged("R_isvip");
					this.OnR_isvipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_BanStatus", DbType="Bit NOT NULL")]
		public bool R_BanStatus
		{
			get
			{
				return this._R_BanStatus;
			}
			set
			{
				if ((this._R_BanStatus != value))
				{
					this.OnR_BanStatusChanging(value);
					this.SendPropertyChanging();
					this._R_BanStatus = value;
					this.SendPropertyChanged("R_BanStatus");
					this.OnR_BanStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_register_date", DbType="DateTime NOT NULL")]
		public System.DateTime R_register_date
		{
			get
			{
				return this._R_register_date;
			}
			set
			{
				if ((this._R_register_date != value))
				{
					this.OnR_register_dateChanging(value);
					this.SendPropertyChanging();
					this._R_register_date = value;
					this.SendPropertyChanged("R_register_date");
					this.OnR_register_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_EmailVerify", DbType="Bit NOT NULL")]
		public bool R_EmailVerify
		{
			get
			{
				return this._R_EmailVerify;
			}
			set
			{
				if ((this._R_EmailVerify != value))
				{
					this.OnR_EmailVerifyChanging(value);
					this.SendPropertyChanging();
					this._R_EmailVerify = value;
					this.SendPropertyChanged("R_EmailVerify");
					this.OnR_EmailVerifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="readers_Favourite", Storage="_Favourites", ThisKey="R_Id", OtherKey="R_Id")]
		public EntitySet<Favourite> Favourites
		{
			get
			{
				return this._Favourites;
			}
			set
			{
				this._Favourites.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="readers_payment", Storage="_payments", ThisKey="R_Id", OtherKey="R_Id")]
		public EntitySet<payment> payments
		{
			get
			{
				return this._payments;
			}
			set
			{
				this._payments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Favourites(Favourite entity)
		{
			this.SendPropertyChanging();
			entity.readers = this;
		}
		
		private void detach_Favourites(Favourite entity)
		{
			this.SendPropertyChanging();
			entity.readers = null;
		}
		
		private void attach_payments(payment entity)
		{
			this.SendPropertyChanging();
			entity.readers = this;
		}
		
		private void detach_payments(payment entity)
		{
			this.SendPropertyChanging();
			entity.readers = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Episode")]
	public partial class Episode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_Id;
		
		private string _E_Title;
		
		private int _E_PageNumber;
		
		private System.DateTime _E_DateUpload;
		
		private char _E_Status;
		
		private int _C_Id;
		
		private EntityRef<Comic> _Comic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_IdChanging(int value);
    partial void OnE_IdChanged();
    partial void OnE_TitleChanging(string value);
    partial void OnE_TitleChanged();
    partial void OnE_PageNumberChanging(int value);
    partial void OnE_PageNumberChanged();
    partial void OnE_DateUploadChanging(System.DateTime value);
    partial void OnE_DateUploadChanged();
    partial void OnE_StatusChanging(char value);
    partial void OnE_StatusChanged();
    partial void OnC_IdChanging(int value);
    partial void OnC_IdChanged();
    #endregion
		
		public Episode()
		{
			this._Comic = default(EntityRef<Comic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int E_Id
		{
			get
			{
				return this._E_Id;
			}
			set
			{
				if ((this._E_Id != value))
				{
					this.OnE_IdChanging(value);
					this.SendPropertyChanging();
					this._E_Id = value;
					this.SendPropertyChanged("E_Id");
					this.OnE_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string E_Title
		{
			get
			{
				return this._E_Title;
			}
			set
			{
				if ((this._E_Title != value))
				{
					this.OnE_TitleChanging(value);
					this.SendPropertyChanging();
					this._E_Title = value;
					this.SendPropertyChanged("E_Title");
					this.OnE_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_PageNumber", DbType="Int NOT NULL")]
		public int E_PageNumber
		{
			get
			{
				return this._E_PageNumber;
			}
			set
			{
				if ((this._E_PageNumber != value))
				{
					this.OnE_PageNumberChanging(value);
					this.SendPropertyChanging();
					this._E_PageNumber = value;
					this.SendPropertyChanged("E_PageNumber");
					this.OnE_PageNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DateUpload", DbType="DateTime NOT NULL")]
		public System.DateTime E_DateUpload
		{
			get
			{
				return this._E_DateUpload;
			}
			set
			{
				if ((this._E_DateUpload != value))
				{
					this.OnE_DateUploadChanging(value);
					this.SendPropertyChanging();
					this._E_DateUpload = value;
					this.SendPropertyChanged("E_DateUpload");
					this.OnE_DateUploadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Status", DbType="Char(1) NOT NULL")]
		public char E_Status
		{
			get
			{
				return this._E_Status;
			}
			set
			{
				if ((this._E_Status != value))
				{
					this.OnE_StatusChanging(value);
					this.SendPropertyChanging();
					this._E_Status = value;
					this.SendPropertyChanged("E_Status");
					this.OnE_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int C_Id
		{
			get
			{
				return this._C_Id;
			}
			set
			{
				if ((this._C_Id != value))
				{
					if (this._Comic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnC_IdChanging(value);
					this.SendPropertyChanging();
					this._C_Id = value;
					this.SendPropertyChanged("C_Id");
					this.OnC_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comic_Episode", Storage="_Comic", ThisKey="C_Id", OtherKey="C_Id", IsForeignKey=true)]
		public Comic Comic
		{
			get
			{
				return this._Comic.Entity;
			}
			set
			{
				Comic previousValue = this._Comic.Entity;
				if (((previousValue != value) 
							|| (this._Comic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Comic.Entity = null;
						previousValue.Episodes.Remove(this);
					}
					this._Comic.Entity = value;
					if ((value != null))
					{
						value.Episodes.Add(this);
						this._C_Id = value.C_Id;
					}
					else
					{
						this._C_Id = default(int);
					}
					this.SendPropertyChanged("Comic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comic")]
	public partial class Comic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _C_Id;
		
		private string _C_Title;
		
		private string _C_Description;
		
		private decimal _C_Price;
		
		private System.DateTime _C_Publish_Date;
		
		private char _C_Status;
		
		private int _C_AgeRestrict;
		
		private bool _C_IsForVip;
		
		private string _C_category;
		
		private int _CC_Id;
		
		private bool _C_CantViewable;
		
		private EntitySet<Favourite> _Favourites;
		
		private EntitySet<Episode> _Episodes;
		
		private EntitySet<payment> _payments;
		
		private EntityRef<Category> _Category;
		
		private EntityRef<ComicCreator> _ComicCreator;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnC_IdChanging(int value);
    partial void OnC_IdChanged();
    partial void OnC_TitleChanging(string value);
    partial void OnC_TitleChanged();
    partial void OnC_DescriptionChanging(string value);
    partial void OnC_DescriptionChanged();
    partial void OnC_PriceChanging(decimal value);
    partial void OnC_PriceChanged();
    partial void OnC_Publish_DateChanging(System.DateTime value);
    partial void OnC_Publish_DateChanged();
    partial void OnC_StatusChanging(char value);
    partial void OnC_StatusChanged();
    partial void OnC_AgeRestrictChanging(int value);
    partial void OnC_AgeRestrictChanged();
    partial void OnC_IsForVipChanging(bool value);
    partial void OnC_IsForVipChanged();
    partial void OnC_categoryChanging(string value);
    partial void OnC_categoryChanged();
    partial void OnCC_IdChanging(int value);
    partial void OnCC_IdChanged();
    partial void OnC_CantViewableChanging(bool value);
    partial void OnC_CantViewableChanged();
    #endregion
		
		public Comic()
		{
			this._Favourites = new EntitySet<Favourite>(new Action<Favourite>(this.attach_Favourites), new Action<Favourite>(this.detach_Favourites));
			this._Episodes = new EntitySet<Episode>(new Action<Episode>(this.attach_Episodes), new Action<Episode>(this.detach_Episodes));
			this._payments = new EntitySet<payment>(new Action<payment>(this.attach_payments), new Action<payment>(this.detach_payments));
			this._Category = default(EntityRef<Category>);
			this._ComicCreator = default(EntityRef<ComicCreator>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int C_Id
		{
			get
			{
				return this._C_Id;
			}
			set
			{
				if ((this._C_Id != value))
				{
					this.OnC_IdChanging(value);
					this.SendPropertyChanging();
					this._C_Id = value;
					this.SendPropertyChanged("C_Id");
					this.OnC_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Title", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string C_Title
		{
			get
			{
				return this._C_Title;
			}
			set
			{
				if ((this._C_Title != value))
				{
					this.OnC_TitleChanging(value);
					this.SendPropertyChanging();
					this._C_Title = value;
					this.SendPropertyChanged("C_Title");
					this.OnC_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string C_Description
		{
			get
			{
				return this._C_Description;
			}
			set
			{
				if ((this._C_Description != value))
				{
					this.OnC_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._C_Description = value;
					this.SendPropertyChanged("C_Description");
					this.OnC_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Price", DbType="Decimal(12,2) NOT NULL")]
		public decimal C_Price
		{
			get
			{
				return this._C_Price;
			}
			set
			{
				if ((this._C_Price != value))
				{
					this.OnC_PriceChanging(value);
					this.SendPropertyChanging();
					this._C_Price = value;
					this.SendPropertyChanged("C_Price");
					this.OnC_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Publish_Date", DbType="DateTime NOT NULL")]
		public System.DateTime C_Publish_Date
		{
			get
			{
				return this._C_Publish_Date;
			}
			set
			{
				if ((this._C_Publish_Date != value))
				{
					this.OnC_Publish_DateChanging(value);
					this.SendPropertyChanging();
					this._C_Publish_Date = value;
					this.SendPropertyChanged("C_Publish_Date");
					this.OnC_Publish_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Status", DbType="Char(1) NOT NULL")]
		public char C_Status
		{
			get
			{
				return this._C_Status;
			}
			set
			{
				if ((this._C_Status != value))
				{
					this.OnC_StatusChanging(value);
					this.SendPropertyChanging();
					this._C_Status = value;
					this.SendPropertyChanged("C_Status");
					this.OnC_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_AgeRestrict", DbType="Int NOT NULL")]
		public int C_AgeRestrict
		{
			get
			{
				return this._C_AgeRestrict;
			}
			set
			{
				if ((this._C_AgeRestrict != value))
				{
					this.OnC_AgeRestrictChanging(value);
					this.SendPropertyChanging();
					this._C_AgeRestrict = value;
					this.SendPropertyChanged("C_AgeRestrict");
					this.OnC_AgeRestrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_IsForVip", DbType="Bit NOT NULL")]
		public bool C_IsForVip
		{
			get
			{
				return this._C_IsForVip;
			}
			set
			{
				if ((this._C_IsForVip != value))
				{
					this.OnC_IsForVipChanging(value);
					this.SendPropertyChanging();
					this._C_IsForVip = value;
					this.SendPropertyChanged("C_IsForVip");
					this.OnC_IsForVipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_category", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string C_category
		{
			get
			{
				return this._C_category;
			}
			set
			{
				if ((this._C_category != value))
				{
					if (this._Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnC_categoryChanging(value);
					this.SendPropertyChanging();
					this._C_category = value;
					this.SendPropertyChanged("C_category");
					this.OnC_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_Id", DbType="Int NOT NULL")]
		public int CC_Id
		{
			get
			{
				return this._CC_Id;
			}
			set
			{
				if ((this._CC_Id != value))
				{
					if (this._ComicCreator.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCC_IdChanging(value);
					this.SendPropertyChanging();
					this._CC_Id = value;
					this.SendPropertyChanged("CC_Id");
					this.OnCC_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CantViewable", DbType="Bit NOT NULL")]
		public bool C_CantViewable
		{
			get
			{
				return this._C_CantViewable;
			}
			set
			{
				if ((this._C_CantViewable != value))
				{
					this.OnC_CantViewableChanging(value);
					this.SendPropertyChanging();
					this._C_CantViewable = value;
					this.SendPropertyChanged("C_CantViewable");
					this.OnC_CantViewableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comic_Favourite", Storage="_Favourites", ThisKey="C_Id", OtherKey="C_Id")]
		public EntitySet<Favourite> Favourites
		{
			get
			{
				return this._Favourites;
			}
			set
			{
				this._Favourites.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comic_Episode", Storage="_Episodes", ThisKey="C_Id", OtherKey="C_Id")]
		public EntitySet<Episode> Episodes
		{
			get
			{
				return this._Episodes;
			}
			set
			{
				this._Episodes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comic_payment", Storage="_payments", ThisKey="C_Id", OtherKey="C_Id")]
		public EntitySet<payment> payments
		{
			get
			{
				return this._payments;
			}
			set
			{
				this._payments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Comic", Storage="_Category", ThisKey="C_category", OtherKey="Ca_Id", IsForeignKey=true)]
		public Category Category
		{
			get
			{
				return this._Category.Entity;
			}
			set
			{
				Category previousValue = this._Category.Entity;
				if (((previousValue != value) 
							|| (this._Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Category.Entity = null;
						previousValue.Comics.Remove(this);
					}
					this._Category.Entity = value;
					if ((value != null))
					{
						value.Comics.Add(this);
						this._C_category = value.Ca_Id;
					}
					else
					{
						this._C_category = default(string);
					}
					this.SendPropertyChanged("Category");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ComicCreator_Comic", Storage="_ComicCreator", ThisKey="CC_Id", OtherKey="CC_Id", IsForeignKey=true)]
		public ComicCreator ComicCreator
		{
			get
			{
				return this._ComicCreator.Entity;
			}
			set
			{
				ComicCreator previousValue = this._ComicCreator.Entity;
				if (((previousValue != value) 
							|| (this._ComicCreator.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ComicCreator.Entity = null;
						previousValue.Comics.Remove(this);
					}
					this._ComicCreator.Entity = value;
					if ((value != null))
					{
						value.Comics.Add(this);
						this._CC_Id = value.CC_Id;
					}
					else
					{
						this._CC_Id = default(int);
					}
					this.SendPropertyChanged("ComicCreator");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Favourites(Favourite entity)
		{
			this.SendPropertyChanging();
			entity.Comic = this;
		}
		
		private void detach_Favourites(Favourite entity)
		{
			this.SendPropertyChanging();
			entity.Comic = null;
		}
		
		private void attach_Episodes(Episode entity)
		{
			this.SendPropertyChanging();
			entity.Comic = this;
		}
		
		private void detach_Episodes(Episode entity)
		{
			this.SendPropertyChanging();
			entity.Comic = null;
		}
		
		private void attach_payments(payment entity)
		{
			this.SendPropertyChanging();
			entity.Comic = this;
		}
		
		private void detach_payments(payment entity)
		{
			this.SendPropertyChanging();
			entity.Comic = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Payment")]
	public partial class payment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _P_Id;
		
		private decimal _P_Amount;
		
		private string _P_Method;
		
		private string _P_Currency;
		
		private System.DateTime _P_Transaction_Date;
		
		private System.Nullable<int> _C_Id;
		
		private int _R_Id;
		
		private string _P_Type;
		
		private EntityRef<Comic> _Comic;
		
		private EntityRef<readers> _readers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_IdChanging(int value);
    partial void OnP_IdChanged();
    partial void OnP_AmountChanging(decimal value);
    partial void OnP_AmountChanged();
    partial void OnP_MethodChanging(string value);
    partial void OnP_MethodChanged();
    partial void OnP_CurrencyChanging(string value);
    partial void OnP_CurrencyChanged();
    partial void OnP_Transaction_DateChanging(System.DateTime value);
    partial void OnP_Transaction_DateChanged();
    partial void OnC_IdChanging(System.Nullable<int> value);
    partial void OnC_IdChanged();
    partial void OnR_IdChanging(int value);
    partial void OnR_IdChanged();
    partial void OnP_TypeChanging(string value);
    partial void OnP_TypeChanged();
    #endregion
		
		public payment()
		{
			this._Comic = default(EntityRef<Comic>);
			this._readers = default(EntityRef<readers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int P_Id
		{
			get
			{
				return this._P_Id;
			}
			set
			{
				if ((this._P_Id != value))
				{
					this.OnP_IdChanging(value);
					this.SendPropertyChanging();
					this._P_Id = value;
					this.SendPropertyChanged("P_Id");
					this.OnP_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Amount", DbType="Decimal(12,2) NOT NULL")]
		public decimal P_Amount
		{
			get
			{
				return this._P_Amount;
			}
			set
			{
				if ((this._P_Amount != value))
				{
					this.OnP_AmountChanging(value);
					this.SendPropertyChanging();
					this._P_Amount = value;
					this.SendPropertyChanged("P_Amount");
					this.OnP_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Method", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Method
		{
			get
			{
				return this._P_Method;
			}
			set
			{
				if ((this._P_Method != value))
				{
					this.OnP_MethodChanging(value);
					this.SendPropertyChanging();
					this._P_Method = value;
					this.SendPropertyChanged("P_Method");
					this.OnP_MethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Currency", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Currency
		{
			get
			{
				return this._P_Currency;
			}
			set
			{
				if ((this._P_Currency != value))
				{
					this.OnP_CurrencyChanging(value);
					this.SendPropertyChanging();
					this._P_Currency = value;
					this.SendPropertyChanged("P_Currency");
					this.OnP_CurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Transaction_Date", DbType="DateTime NOT NULL")]
		public System.DateTime P_Transaction_Date
		{
			get
			{
				return this._P_Transaction_Date;
			}
			set
			{
				if ((this._P_Transaction_Date != value))
				{
					this.OnP_Transaction_DateChanging(value);
					this.SendPropertyChanging();
					this._P_Transaction_Date = value;
					this.SendPropertyChanged("P_Transaction_Date");
					this.OnP_Transaction_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Id", DbType="Int")]
		public System.Nullable<int> C_Id
		{
			get
			{
				return this._C_Id;
			}
			set
			{
				if ((this._C_Id != value))
				{
					if (this._Comic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnC_IdChanging(value);
					this.SendPropertyChanging();
					this._C_Id = value;
					this.SendPropertyChanged("C_Id");
					this.OnC_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Id", DbType="Int NOT NULL")]
		public int R_Id
		{
			get
			{
				return this._R_Id;
			}
			set
			{
				if ((this._R_Id != value))
				{
					if (this._readers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnR_IdChanging(value);
					this.SendPropertyChanging();
					this._R_Id = value;
					this.SendPropertyChanged("R_Id");
					this.OnR_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Type", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string P_Type
		{
			get
			{
				return this._P_Type;
			}
			set
			{
				if ((this._P_Type != value))
				{
					this.OnP_TypeChanging(value);
					this.SendPropertyChanging();
					this._P_Type = value;
					this.SendPropertyChanged("P_Type");
					this.OnP_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comic_payment", Storage="_Comic", ThisKey="C_Id", OtherKey="C_Id", IsForeignKey=true)]
		public Comic Comic
		{
			get
			{
				return this._Comic.Entity;
			}
			set
			{
				Comic previousValue = this._Comic.Entity;
				if (((previousValue != value) 
							|| (this._Comic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Comic.Entity = null;
						previousValue.payments.Remove(this);
					}
					this._Comic.Entity = value;
					if ((value != null))
					{
						value.payments.Add(this);
						this._C_Id = value.C_Id;
					}
					else
					{
						this._C_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Comic");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="readers_payment", Storage="_readers", ThisKey="R_Id", OtherKey="R_Id", IsForeignKey=true)]
		public readers readers
		{
			get
			{
				return this._readers.Entity;
			}
			set
			{
				readers previousValue = this._readers.Entity;
				if (((previousValue != value) 
							|| (this._readers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._readers.Entity = null;
						previousValue.payments.Remove(this);
					}
					this._readers.Entity = value;
					if ((value != null))
					{
						value.payments.Add(this);
						this._R_Id = value.R_Id;
					}
					else
					{
						this._R_Id = default(int);
					}
					this.SendPropertyChanged("readers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ComicPurchased")]
	public partial class ComicPurchased
	{
		
		private System.Nullable<int> _C_Id;
		
		private System.Nullable<int> _Total;
		
		private string _Comic_Name;
		
		private decimal _Price;
		
		private string _Name;
		
		private System.DateTime _Date;
		
		public ComicPurchased()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Id", DbType="Int")]
		public System.Nullable<int> C_Id
		{
			get
			{
				return this._C_Id;
			}
			set
			{
				if ((this._C_Id != value))
				{
					this._C_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comic_Name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Comic_Name
		{
			get
			{
				return this._Comic_Name;
			}
			set
			{
				if ((this._Comic_Name != value))
				{
					this._Comic_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(12,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Member")]
	public partial class Member
	{
		
		private string _Nickname;
		
		private string _Hash;
		
		private string _Email;
		
		private string _Role;
		
		private System.DateTime _Register_Date;
		
		public Member()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="VarChar(50)")]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this._Nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hash", DbType="VarChar(50)")]
		public string Hash
		{
			get
			{
				return this._Hash;
			}
			set
			{
				if ((this._Hash != value))
				{
					this._Hash = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Register Date]", Storage="_Register_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Register_Date
		{
			get
			{
				return this._Register_Date;
			}
			set
			{
				if ((this._Register_Date != value))
				{
					this._Register_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Purchased")]
	public partial class Purchased
	{
		
		private int _R_Id;
		
		private int _C_Id;
		
		private string _C_category;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		public Purchased()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Id", DbType="Int NOT NULL")]
		public int R_Id
		{
			get
			{
				return this._R_Id;
			}
			set
			{
				if ((this._R_Id != value))
				{
					this._R_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Id", DbType="Int NOT NULL")]
		public int C_Id
		{
			get
			{
				return this._C_Id;
			}
			set
			{
				if ((this._C_Id != value))
				{
					this._C_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_category", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string C_category
		{
			get
			{
				return this._C_category;
			}
			set
			{
				if ((this._C_category != value))
				{
					this._C_category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TempCategory")]
	public partial class TempCategory
	{
		
		private string _Ca_Id;
		
		private string _Ca_Name;
		
		public TempCategory()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca_Id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Ca_Id
		{
			get
			{
				return this._Ca_Id;
			}
			set
			{
				if ((this._Ca_Id != value))
				{
					this._Ca_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ca_Name
		{
			get
			{
				return this._Ca_Name;
			}
			set
			{
				if ((this._Ca_Name != value))
				{
					this._Ca_Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopCategory")]
	public partial class TopCategory
	{
		
		private string _Ca_Name;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<int> _Total;
		
		public TopCategory()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ca_Name
		{
			get
			{
				return this._Ca_Name;
			}
			set
			{
				if ((this._Ca_Name != value))
				{
					this._Ca_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ComicInfo")]
	public partial class ComicInfo
	{
		
		private int _C_Id;
		
		private string _C_Title;
		
		private string _CC_NickName;
		
		private int _CC_Id;
		
		private string _C_Description;
		
		private char _C_Status;
		
		private bool _C_CantViewable;
		
		private bool _C_IsForVip;
		
		private int _C_AgeRestrict;
		
		private System.DateTime _C_Publish_Date;
		
		private string _Ca_Name;
		
		public ComicInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Id", DbType="Int NOT NULL")]
		public int C_Id
		{
			get
			{
				return this._C_Id;
			}
			set
			{
				if ((this._C_Id != value))
				{
					this._C_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Title", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string C_Title
		{
			get
			{
				return this._C_Title;
			}
			set
			{
				if ((this._C_Title != value))
				{
					this._C_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_NickName", DbType="VarChar(50)")]
		public string CC_NickName
		{
			get
			{
				return this._CC_NickName;
			}
			set
			{
				if ((this._CC_NickName != value))
				{
					this._CC_NickName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_Id", DbType="Int NOT NULL")]
		public int CC_Id
		{
			get
			{
				return this._CC_Id;
			}
			set
			{
				if ((this._CC_Id != value))
				{
					this._CC_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string C_Description
		{
			get
			{
				return this._C_Description;
			}
			set
			{
				if ((this._C_Description != value))
				{
					this._C_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Status", DbType="Char(1) NOT NULL")]
		public char C_Status
		{
			get
			{
				return this._C_Status;
			}
			set
			{
				if ((this._C_Status != value))
				{
					this._C_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CantViewable", DbType="Bit NOT NULL")]
		public bool C_CantViewable
		{
			get
			{
				return this._C_CantViewable;
			}
			set
			{
				if ((this._C_CantViewable != value))
				{
					this._C_CantViewable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_IsForVip", DbType="Bit NOT NULL")]
		public bool C_IsForVip
		{
			get
			{
				return this._C_IsForVip;
			}
			set
			{
				if ((this._C_IsForVip != value))
				{
					this._C_IsForVip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_AgeRestrict", DbType="Int NOT NULL")]
		public int C_AgeRestrict
		{
			get
			{
				return this._C_AgeRestrict;
			}
			set
			{
				if ((this._C_AgeRestrict != value))
				{
					this._C_AgeRestrict = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Publish_Date", DbType="DateTime NOT NULL")]
		public System.DateTime C_Publish_Date
		{
			get
			{
				return this._C_Publish_Date;
			}
			set
			{
				if ((this._C_Publish_Date != value))
				{
					this._C_Publish_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ca_Name
		{
			get
			{
				return this._Ca_Name;
			}
			set
			{
				if ((this._Ca_Name != value))
				{
					this._Ca_Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user
	{
		
		private string _Nickname;
		
		private string _Hash;
		
		private string _Email;
		
		private string _Role;
		
		private bool _Status;
		
		public user()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="VarChar(50)")]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this._Nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hash", DbType="VarChar(50)")]
		public string Hash
		{
			get
			{
				return this._Hash;
			}
			set
			{
				if ((this._Hash != value))
				{
					this._Hash = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profit")]
	public partial class Profit
	{
		
		private string _R_NickName;
		
		private string _Methold;
		
		private System.Nullable<decimal> _Amount;
		
		private System.DateTime _Date;
		
		public Profit()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_NickName", DbType="VarChar(50)")]
		public string R_NickName
		{
			get
			{
				return this._R_NickName;
			}
			set
			{
				if ((this._R_NickName != value))
				{
					this._R_NickName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Methold", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Methold
		{
			get
			{
				return this._Methold;
			}
			set
			{
				if ((this._Methold != value))
				{
					this._Methold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopComic")]
	public partial class TopComic
	{
		
		private string _Comic_Name;
		
		private string _Name;
		
		private decimal _Price;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<int> _Total;
		
		public TopComic()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comic_Name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Comic_Name
		{
			get
			{
				return this._Comic_Name;
			}
			set
			{
				if ((this._Comic_Name != value))
				{
					this._Comic_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(12,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
